# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/godaddy/tartufo
    rev: v2.10.0
    hooks:
    -   id: tartufo
        exclude: 'docs/'

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: flake8
        args: [ --max-line-length=79, '--ignore=E203,W503' ]
        exclude: 'docs/'
#-   repo: https://github.com/psf/black
#    rev: 19.3b0
#    hooks:
#    -   id: black
-   repo: https://github.com/pycqa/pylint
    rev: v2.11.1
    hooks:
    -   id: pylint
        exclude: 'tests/'
        args: [
            --max-line-length=79,
            --disable=design,
            --disable=missing-docstring,
            --disable=bad-continuation,
            --disable=max-module-lines,
            --disable=useless-super-delegation,
            --disable=import-error,
            --disable=logging-fstring-interpolation,
            --disable=invalid-name,
            --disable=duplicate-code,
            --disable=broad-except,
            --disable=logging-format-interpolation,
            --disable=too-many-lines
        ]

-   repo: https://github.com/pycqa/isort
    rev: 5.9.0
    hooks:
    -   id: isort
        args: [--profile, black, --line-length=79]
        exclude: 'docs/'
